#!/bin/bash

theDATE=`date +%F-%Hh%mm%Ss`
echo "[gmv-msg]:$theDATE:Hello World"
echo "$theDATE Not in textbox"
echo "[gmv-msg]:$theDATE:Re-Hello World"
echo "[gmv-msg]:$theDATE:I told you hello"
echo "[gmv-msg]:$theDATE:I said hello"
echo "[gmv-msg]:$theDATE:Hello World"
echo "$theDATE:Not in textbox"
echo "[gmv-msg]:$theDATE:Re-Hello World"
echo "[gmv-msg]:$theDATE:I told you hello"
echo "[gmv-msg]:$theDATE:I said hello"
echo "[gmv-msg]:$theDATE:hello World"
echo "$theDATE:Not in textbox"
echo "[gmv-msg]:$theDATE:Re-Hello World"
echo "[gmv-msg]:$theDATE:I told you hello"
echo "[gmv-msg]:$theDATE:I said hello"
echo "[gmv-msg]:$theDATE:ello World"
echo "$theDATE:Not in textbox"
echo "[gmv-msg]:$theDATE:Re-Hello World"
echo "[gmv-msg]:$theDATE:I told you hello"
echo "[gmv-msg]:$theDATE:I said hello"
echo "[gmv-msg]:$theDATE:Hello World"
echo "$theDATE:Not in textbox"
sleep 20
theDATE=`date +%F-%Hh%mm%Ss`
echo "[gmv-msg]:$theDATE:Re-Hello World"
echo "[gmv-msg]:$theDATE:I told you hello"
echo "[gmv-msg]:$theDATE:I said hello"
echo "[gmv-msg]:$theDATE:Hello World"
echo "$theDATE:Not in textbox"
echo "[gmv-msg]:$theDATE:Re-Hello World"
echo "[gmv-msg]:$theDATE:I told you hello"
echo "[gmv-msg]:$theDATE:I said hello"
echo "[gmv-msg]:$theDATE:Hello World"
echo "$theDATE:Not in textbox"
echo "[gmv-msg]:$theDATE:Re-Hello World"
echo "[gmv-msg]:$theDATE:I told you hello"
echo "[gmv-msg]:$theDATE:I said hello"
